############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = "/"
weight = 1

[[main]]
name = "AIxCC Team"
url = "authors/"
weight = 2
hasChildren = true

[[main]]
name = "Research & Code"
url = "artifacts/"
weight = 3

[[main]]
name = "News"
url = "news/"
weight = 4

[[main]]
name = "Blog"
url = "blog/"
weight = 5

#[[main]]
#name = "Contact"
#url = "contact/"
#weight = 6

#[[main]]
#name = "Elements"
#url = "elements/"
#weight = 3

#[[main]]
#weight = 4
#name = "Pages"
#hasChildren = true

#[[main]]
#parent = "Pages"
#name = "Contact"
#url = "contact/"

[[main]]
parent = "AIxCC Team"
name = "Team Leader"
url = "authors/#team-leader"
weight = 1

[[main]]
parent = "AIxCC Team"
name = "Atlantis-Multilang"
url = "authors/#team-multilang"
weight = 2

[[main]]
parent = "AIxCC Team"
name = "Atlantis-C"
url = "authors/#team-c"
weight = 3

[[main]]
parent = "AIxCC Team"
name = "Atlantis-Java"
url = "authors/#team-java"
weight = 4

[[main]]
parent = "AIxCC Team"
name = "Atlantis-Patch"
url = "authors/#team-patch"
weight = 5

[[main]]
parent = "AIxCC Team"
name = "Atlantis-SARIF"
url = "authors/#team-sarif"
weight = 6

[[main]]
parent = "AIxCC Team"
name = "Atlantis-Infra"
url = "authors/#team-infra"
weight = 7

#[[main]]
#parent = "Pages"
#name = "Categories"
#url = "categories/"

#[[main]]
#parent = "Pages"
#name = "404 Page"
#url = "404/"


# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "AIxCC Team"
url = "authors/"
weight = 2

[[footer]]
name = "Research & Code"
url = "artifacts/"
weight = 3

[[footer]]
name = "News"
url = "news/"
weight = 4

[[footer]]
name = "Blog"
url = "blog/"
weight = 5

#[[footer]]
#name = "Contact"
#url = "contact/"
#weight = 6

#[[footer]]
#name = "Elements"
#url = "elements/"
#weight = 7

#[[footer]]
#name = "Privacy Policy"
#url = "privacy-policy/"
#weight = 8
